# Generated by Django 4.2.10 on 2024-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completedItems',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='electricity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='shutDownCount',
            field=models.IntegerField(),
        ),
    ]
