# Generated by Django 4.2.10 on 2024-02-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_completeditems_alter_user_electricity_and_more'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='electricityConsume',
            field=models.IntegerField(),
        ),
    ]
