# Generated by Django 4.2.10 on 2024-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0002_item_itemuser_alter_item_electricityconsume'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ddl',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
