# Generated by Django 4.2.10 on 2024-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0003_item_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
